language: go

matrix:
  fast_finish: true
  include:
    - go: 1.14.x
    - go: 1.15.x
    - go: master

install:
  - go get github.com/golang/glog
  - go get -v .
  - go get -v golang.org/x/lint/golint

script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint -set_exit_status ./...
  - go test -v -race ./...
  - go run ./.example/main.go
