language: go

matrix:
  fast_finish: true
  include:
    - go: 1.11.x
      env: GO111MODULE=on
    - go: 1.12.x
      env: GO111MODULE=on
    - go: 1.13.x
    - go: 1.14.x
    - go: 1.15.x
    - go: master

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi

install:
  - go get github.com/golang/glog
  - go get -v .
  - go get -v golang.org/x/lint/golint

script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint -set_exit_status ./...
  - go test -v -race ./...
  - go run ./.example/main.go
